### ISSUE TITLE
Nest doorbell stream has no audio

### ISSUE THREAD

**Issue by backslashV** [felipecrs/hass-expose-camera-stream-source#33]
Hi,
How can I add audio to the stream? I have the following config in Frigate still with no audio.
```
go2rtc:
  streams:
    doorbell:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.doorbell
      - "ffmpeg:back#audio=aac"
```
