### ISSUE TITLE
Adding still image cameras to go2rtc

### ISSUE THREAD

**Issue by felipecrs** [felipecrs/hass-expose-camera-stream-source#53]
Initially reported by @incline02 [here](https://github.com/felipecrs/hass-expose-camera-stream-source/issues/51#issuecomment-2905122121).

---

This integration simply exposes the `stream_source` for a Home Assistant camera so that you can use in somewhere else like go2rtc.

However, some camera integrations do not implement `stream_source` and there is nothing this integration can do for you.

However, if a still image is provided for your camera, you can still add them to go2rtc like this:

```yaml
stream:
  my_camera:
    - "http://supervisor/core/api/camera_proxy/camera.my_camera#header=Authorization: Bearer ${SUPERVISOR_TOKEN}"
    - ffmpeg:my_camera#video=h264#input=--re -stream_loop -1 -f image2 -framerate 1 -i {input}
```

The above will poll Home Assistant for a new JPEG image every second and convert that into a H264 stream.

Remember to replace `camera.my_camera` with your camera entity ID.

Note you do **not** need to replace `${SUPERVISOR_TOKEN}` in this URL, just use it as is.

However, if not running this through the go2rtc or Frigate add-on, just replace `http://supervisor/core` with your Home Assistant HTTP address, and `${SUPERVISOR_TOKEN}` with a long-lived access token.
