### ISSUE TITLE
Recommended install with frigate 0.12 and gortc built in?

### ISSUE THREAD

**Issue by SgtBatten** [felipecrs/hass-expose-camera-stream-source#6]
Hi, I am wondering if there is a different or recommended way of running this now that frigate is using gortc internally?

**Comment by felipecrs** [comment]
Hi there. No, it works pretty much the same, it's just simpler. The Frigate beta add-on has already the needed accesses for using this integration:

- https://github.com/blakeblackshear/frigate-hass-addons/pull/94

Once it gets released to stable, I'll update the guide on the main page.

**Comment by felipecrs** [comment]
Anyway, here's an example if you are using Frigate 0.12:

```yaml
# frigate.yaml

go2rtc:
  streams:
    my_camera:
      - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.my_camera
      # Do the audio conversion if you need 
      - ffmpeg:my_camera#audio=aac 

cameras:
  video_porteiro:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/my_camera?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/my_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

**Comment by SgtBatten** [comment]
Thanks, Is this still applicable if frigate is not an addon. I run it on unraid. I've tried all 3 methods so far without luck.

**Comment by felipecrs** [comment]
If you run without being an add-on, then you should follow this:

https://github.com/felipecrs/hass-expose-camera-stream-source#when-go2rtc-is-running-via-docker

**Comment by felipecrs** [comment]
But you have to tailor it to the Frigate container.

**Comment by felipecrs** [comment]
Was it working before Frigate 0.12?

**Comment by felipecrs** [comment]
What camera do you have?

**Comment by SgtBatten** [comment]
No first time i'm trying to incorporate this camera at all. I tried a year ago but i didn't realise progress had been made to get tuya cams into HA til today. 

I have this camera: https://www.kogan.com/au/buy/kogan-smarterhome-smart-baby-monitor-security-camera-white-kogan/?utm_source=google&utm_medium=product_listing_ads

I have added it to the tuya app and it has appeared in home assistant. I've renamed it to camera.bed_3_baby_monitor

I am running frigate beta 5 in a container. I don't have access to the gortc docker config like in your guide due to it being built into the frigate container. So what i did was add the long lived token to the frigate container as an ENV variable, and add the get_ha_streams.sh to the appdata/frigate folder which contains the frigate.yml file and is mapped to the /config folder in the frigate container.

**Comment by SgtBatten** [comment]
I suspect (with my limited knowledge) that gortc config folder is not the same one mapped to frigate config

**Comment by felipecrs** [comment]
There's no such thing anymore. The go2rtc config is embedded in the frigate config under `go2rtc:` key.

**Comment by SgtBatten** [comment]
```
go2rtc:
  streams:
    baby_monitor:
      - echo:/config/get_ha_stream.sh camera.bed_3_baby_monitor
      #- echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.bed_3_baby_monitor
      - ffmpeg:baby_monitor#audio=aac
  ```

```
cameras:
  baby_monitor:
    ffmpeg:
      inputs:
        - path: rtsp://localhost:8554/baby_monitor?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://localhost:8554/baby_monitor?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
   ```
